### PR TITLE
Patch 2

### PR DESCRIPTION
**Pull request by PyRowMan**
This PR is linked to the issue https://github.com/Combodo/CombodoPayumStripe/issues/2

There is several changements : 

- Using the targetUrl (capture route) in the obtainTokenAction instead of the afterUrl as success_url & cancel_url in order to recover the payment status directly after the payment.
- Add a condition in the captureAction in order to catch the request when the payment is done
- Add a new CheckPayment action
- Add a RefundAction
- Fix the missing class "Constants" in StatusAction
- Remove some conditions to allow the payment to be captured in StatusAction

### CODE REVIEW

**Comment by bruno-ds** [comment]
I've made my own implementation of the paiement recovery after paiement, I polish it a little and push it into a branch on order to see together what to do.

**Comment by bruno-ds** [comment]
there it is : 
https://github.com/Combodo/CombodoPayumStripe/compare/feature/payment_recovery_after_pay

1/ in `ObtainTokenAction.php` the code is huge only because I tried to cover both `?` and `&` 

2/ in `CaptureAction.php` the magic is done by adding a call to the new `handleIfPaymentDone()` before the normal flow

It is plugged onto `handleCheckoutCompletedEvent` so the normal payment workflow is maintained (`StripeV3UpdatePaymentStateOnCheckoutCompletedEvent` is still called)

**Comment by PyRowMan** [comment]
I'm on it, I should give a feedback tomorrow, don't worry.

**Comment by bruno-ds** [comment]
well, that's vexing: I just installed ngrock, and I didn't notice that there is a race condition: 
the token is deleted by the webhook, so the redirection to `/payment/capture/{tokenHash}` fails with 
> A token with hash `theTokenHashIsHere` could not be found.
 
I just cannot figure out a smart solution for now, every and each solution that come to my mind require either 
 - to change (decorate) the behaviour of a controller (either the payum's `CaptureController` or sylis' `ThankYou` controller
 - to not delete the token on the webhook side (but then, when should we delete it ? ...)

**Pull request closed without merging**
